#!/bin/bash                         #-- what is the language of this shell
#                                  #-- Any line that starts with #$ is an instruction to SGE
#$ -S /bin/bash                     #-- the shell for the job
#$ -o output_error_directory       #-- output directory (fill in)
#$ -e output_error_directory       #-- error directory (fill in)
#$ -cwd                            #-- tell the job that it should start in your working directory
#$ -r y                            #-- tell the system that if a job crashes, it should be restarted
#$ -j y                            #-- tell the system that the STDERR and STDOUT should be joined
#$ -l mem_free=1G                  #-- submits on nodes with enough free memory (required)
#$ -l arch=linux-x64               #-- SGE resources (CPU type)
#$ -l netapp=1G,scratch=1G         #-- SGE resources (home and scratch disks)
#$ -l h_rt=100:00:00                #-- runtime limit (see above; this requests 24 hours)
#$ -t 1-151                        #-- remove first '#' to specify the number of
                                   #-- tasks if desired (see Tips section)

#readarray files < /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/species_snps.txt
readarray files < /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/Qin_HMP/snps_olddb_time_controlled/species_snps.txt

files=(null ${files[@]}) # this pads the file with an extra line in the beginning. 
species=${files[$SGE_TASK_ID]}

#bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/${species}/snps_depth.txt
#bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/${species}/snps_info.txt
#bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/${species}/snps_ref_freq.txt
#bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/snps/${species}/snps_alt_allele.txt

bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/Qin_HMP/snps_olddb_time_controlled/${species}/snps_depth.txt
bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/Qin_HMP/snps_olddb_time_controlled/${species}/snps_info.txt
bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/Qin_HMP/snps_olddb_time_controlled/${species}/snps_ref_freq.txt
bzip2 /netapp/home/ngarud/shattuck/BenNanditaProject/ben_nandita_hmp_data/Qin_HMP/snps_olddb_time_controlled/${species}/snps_alt_allele.txt
