#!/bin/bash                         #-- what is the language of this shell
#                                  #-- Any line that starts with #$ is an instruction to SGE
#$ -S /bin/bash                     #-- the shell for the job
#$ -o output_error_directory       #-- output directory (fill in)
#$ -e output_error_directory       #-- error directory (fill in)
#$ -cwd                            #-- tell the job that it should start in your working directory
#$ -r y                            #-- tell the system that if a job crashes, it should be restarted
#$ -j y                            #-- tell the system that the STDERR and STDOUT should be joined
#$ -l mem_free=1G                  #-- submits on nodes with enough free memory (required)
#$ -l arch=linux-x64               #-- SGE resources (CPU type)
#$ -l netapp=1G,scratch=1G         #-- SGE resources (home and scratch disks)
#$ -l h_rt=336:00:00               #-- runtime limit (see above; this requests 24 hours)
#$ -t 1-6                        #-- remove first '#' to specify the number of
                                   #-- tasks if desired (see Tips section)

readarray genomes < ~/shattuck/BenNanditaProject/MIDAS_ref_genome_test/B_uniformis_genome_ids.txt

genomes=(null ${genomes[@]}) # this pads the file with an extra line in the beginning. 
genome_id=${genomes[$SGE_TASK_ID]}
echo $genome_id

file=700037453
mkdir /netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_ref_genome_test/MIDAS_output/${genome_id}
OUTDIR=/netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_ref_genome_test/MIDAS_output/${genome_id}/${file}
mkdir $OUTDIR

# species
run_midas.py species $OUTDIR -1 /netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_tech_reps/${file}_1.fastq.gz -2 /netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_tech_reps/${file}_2.fastq.gz -d ~/shattuck/BenNanditaProject/MIDAS_ref_genome_test/midas_db_new_ref_genomes/midas_db_${genome_id}


# snps
run_midas.py snps $OUTDIR -1 /netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_tech_reps/${file}_1.fastq.gz -2 /netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_tech_reps/${file}_2.fastq.gz -d ~/shattuck/BenNanditaProject/MIDAS_ref_genome_test/midas_db_new_ref_genomes/midas_db_${genome_id}

