#!/bin/bash                         #-- what is the language of this shell
#                                  #-- Any line that starts with #$ is an instruction to SGE
#$ -S /bin/bash                     #-- the shell for the job
#$ -o output_error_directory       #-- output directory (fill in)
#$ -e output_error_directory       #-- error directory (fill in)
#$ -cwd                            #-- tell the job that it should start in your working directory
#$ -r y                            #-- tell the system that if a job crashes, it should be restarted
#$ -j y                            #-- tell the system that the STDERR and STDOUT should be joined
#$ -l mem_free=3G                  #-- submits on nodes with enough free memory (required)
#$ -l arch=linux-x64               #-- SGE resources (CPU type)
#$ -l netapp=1G,scratch=1G         #-- SGE resources (home and scratch disks)
#$ -l h_rt=336:00:00               #-- runtime limit (see above; this requests 24 hours)
#$ -t 1-186                        #-- remove first '#' to specify the number of
                                   #-- tasks if desired (see Tips section)

readarray files < ~/shattuck/BenNanditaProject/MIDAS_intermediate_files_Qin_2012/sample_IDs_healthy.txt


files=(null ${files[@]}) # this pads the file with an extra line in the beginning. 
file=${files[$SGE_TASK_ID]}
echo $file

OUTDIR=/netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_Qin_2012/MIDAS_1.2.2_output/${file}

mkdir $OUTDIR

INDIR=/pollard/shattuck0/snayfach/metagenomes/T2D/fastq

run_midas.py species $OUTDIR -1 ${INDIR}/${file}_1.fastq.gz -2 ${INDIR}/${file}_2.fastq.gz
run_midas.py snps $OUTDIR -1 ${INDIR}/${file}_1.fastq.gz -2 ${INDIR}/${file}_2.fastq.gz
run_midas.py genes $OUTDIR -1 ${INDIR}/${file}_1.fastq.gz -2 ${INDIR}/${file}_2.fastq.gz


