#!/bin/bash                         #-- what is the language of this shell
#                                  #-- Any line that starts with #$ is an instruction to SGE
#$ -S /bin/bash                     #-- the shell for the job
#$ -o output_error_directory       #-- output directory (fill in)
#$ -e output_error_directory       #-- error directory (fill in)
#$ -cwd                            #-- tell the job that it should start in your working directory
#$ -r y                            #-- tell the system that if a job crashes, it should be restarted
#$ -j y                            #-- tell the system that the STDERR and STDOUT should be joined
#$ -l mem_free=1G                  #-- submits on nodes with enough free memory (required)
#$ -l arch=linux-x64               #-- SGE resources (CPU type)
#$ -l netapp=1G,scratch=1G         #-- SGE resources (home and scratch disks)
#$ -l h_rt=336:00:00               #-- runtime limit (see above; this requests 24 hours)
#$ -t 1-234                        #-- remove first '#' to specify the number of
                                   #-- tasks if desired (see Tips section)

readarray files < ~/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/sample_paths.txt

files=(null ${files[@]}) # this pads the file with an extra line in the beginning. 
file=${files[$SGE_TASK_ID]}

sample=`echo $file | cut -f9 -d'/'`


echo $sample

#check whether the sample is a merged sample or not (if it has a c at the end, then it is)
# the reason for doing is is to direct midas to the correct path with the relevant fasta files. 
last_character=`echo $sample | sed -e "s/^.*\(.\)$/\1/"`
echo $last_character

if [ "$last_character" == "c" ]
then
path=/netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_sample_reps
else
path=/netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/joined_fastq_files_hmp_combine_tech_reps
fi

OUTDIR=/netapp/home/ngarud/shattuck/BenNanditaProject/MIDAS_intermediate_files_hmp/MIDAS_1.2.2_read_stealing_test/Bacteroides_uniformis_57318/${sample}

run_midas.py snps $OUTDIR -1 ${path}/${sample}_1.fastq.gz -2 ${path}/${sample}_2.fastq.gz --species_id Bacteroides_uniformis_57318

